// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANM1wwbRttNnJRUBvD0TpdNZ1epad7Prw',
    appId: '1:306119479233:web:90c1e0493d181e17a16940',
    messagingSenderId: '306119479233',
    projectId: 'dessenger-63914',
    authDomain: 'dessenger-63914.firebaseapp.com',
    storageBucket: 'dessenger-63914.appspot.com',
    measurementId: 'G-RNWR73SHM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtpqHgjq_21msSdc7vFjrzkr6ULgRBBDg',
    appId: '1:306119479233:android:c35fa5de4fb493a5a16940',
    messagingSenderId: '306119479233',
    projectId: 'dessenger-63914',
    storageBucket: 'dessenger-63914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsfRry1Ru0LoORefVRAtaT9A_CDWKEdmE',
    appId: '1:306119479233:ios:361b1462aecccd38a16940',
    messagingSenderId: '306119479233',
    projectId: 'dessenger-63914',
    storageBucket: 'dessenger-63914.appspot.com',
    androidClientId: '306119479233-d8f2jvfg3rbsh5fju90n3e1k1lheip4g.apps.googleusercontent.com',
    iosClientId: '306119479233-5p4aqe6lqdf0u6vq18f60j4te68tg8eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklistCrudTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsfRry1Ru0LoORefVRAtaT9A_CDWKEdmE',
    appId: '1:306119479233:ios:361b1462aecccd38a16940',
    messagingSenderId: '306119479233',
    projectId: 'dessenger-63914',
    storageBucket: 'dessenger-63914.appspot.com',
    androidClientId: '306119479233-d8f2jvfg3rbsh5fju90n3e1k1lheip4g.apps.googleusercontent.com',
    iosClientId: '306119479233-5p4aqe6lqdf0u6vq18f60j4te68tg8eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklistCrudTest',
  );
}
